<% module_namespacing do -%>
# This controller was generated by RailsPanel generator. Remember to include RailsPanel::Resources in thi class
# or in this class superclass
class <%= controller_class_name %>Controller < ApplicationController
end
<% end %>
